// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using GDev.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GDev.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("GDev.Business.Model.Acesso", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("DiaAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DiaCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ModuloId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Token")
                        .HasColumnName("TOKEN")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Url")
                        .HasColumnName("URL")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModuloId");

                    b.ToTable("ACESSO");
                });

            modelBuilder.Entity("GDev.Business.Model.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("DiaAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DiaCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("RazaoSocial")
                        .HasColumnName("RAZAO_SOCIAL")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA");
                });

            modelBuilder.Entity("GDev.Business.Model.Modulo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("DiaAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DiaCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("MODULO");
                });

            modelBuilder.Entity("GDev.Business.Model.Acesso", b =>
                {
                    b.HasOne("GDev.Business.Model.Cliente", "Cliente")
                        .WithMany("Acessos")
                        .HasForeignKey("ClienteId")
                        .IsRequired();

                    b.HasOne("GDev.Business.Model.Modulo", "Modulo")
                        .WithMany("Acessos")
                        .HasForeignKey("ModuloId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
